"""add ready state to room players

Revision ID: 0f1543e7d899
Revises: 1fa1609502dd
Create Date: 2026-07-09 19:35:22.233529

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0f1543e7d899"
down_revision: Union[str, Sequence[str], None] = "1fa1609502dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "room_players",
        sa.Column("is_ready", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("room_players", "is_ready")
    # ### end Alembic commands ###
