"""update auth identity fields

Revision ID: 1d0aff38d16f
Revises: 61b930199a5d
Create Date: 2026-07-08 21:46:45.771637

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d0aff38d16f"
down_revision: Union[str, Sequence[str], None] = "61b930199a5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_identities",
        sa.Column("provider_subject", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "auth_identities",
        sa.Column("provider_email", sa.String(length=255), nullable=False),
    )
    op.drop_constraint(
        op.f("uq_auth_identity_provider_user"), "auth_identities", type_="unique"
    )
    op.create_unique_constraint(
        "uq_auth_identity_provider_user",
        "auth_identities",
        ["provider", "provider_subject"],
    )
    op.drop_column("auth_identities", "provider_user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_identities",
        sa.Column(
            "provider_user_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        "uq_auth_identity_provider_user", "auth_identities", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_auth_identity_provider_user"),
        "auth_identities",
        ["provider", "provider_user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("auth_identities", "provider_email")
    op.drop_column("auth_identities", "provider_subject")
    # ### end Alembic commands ###
