"""add rooms and room players tables

Revision ID: 6b8b0e6b6de3
Revises: 1d0aff38d16f
Create Date: 2026-07-09 15:33:36.625974

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b8b0e6b6de3"
down_revision: Union[str, Sequence[str], None] = "1d0aff38d16f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=6), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("max_players", sa.Integer(), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rooms_code"), "rooms", ["code"], unique=True)
    op.create_index(op.f("ix_rooms_id"), "rooms", ["id"], unique=False)
    op.create_table(
        "room_players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_id", "user_id", name="uq_room_player"),
    )
    op.create_index(op.f("ix_room_players_id"), "room_players", ["id"], unique=False)
    op.create_index(
        op.f("ix_room_players_room_id"), "room_players", ["room_id"], unique=False
    )
    op.create_index(
        op.f("ix_room_players_user_id"), "room_players", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_room_players_user_id"), table_name="room_players")
    op.drop_index(op.f("ix_room_players_room_id"), table_name="room_players")
    op.drop_index(op.f("ix_room_players_id"), table_name="room_players")
    op.drop_table("room_players")
    op.drop_index(op.f("ix_rooms_id"), table_name="rooms")
    op.drop_index(op.f("ix_rooms_code"), table_name="rooms")
    op.drop_table("rooms")
    # ### end Alembic commands ###
