"""create missions table

Revision ID: 89a683953033
Revises: ddb29766c614
Create Date: 2026-07-10 00:05:35.137566

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89a683953033"
down_revision: Union[str, Sequence[str], None] = "ddb29766c614"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "missions", sa.Column("assigned_to_user_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "missions", sa.Column("mission_type", sa.String(length=50), nullable=False)
    )
    op.add_column("missions", sa.Column("target_value", sa.Integer(), nullable=False))
    op.add_column("missions", sa.Column("current_value", sa.Integer(), nullable=False))
    op.alter_column(
        "missions",
        "description",
        existing_type=sa.TEXT(),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_missions_assigned_to_user_id"),
        "missions",
        ["assigned_to_user_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "missions", "users", ["assigned_to_user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("missions", "is_completed")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "missions",
        sa.Column("is_completed", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "missions", type_="foreignkey")
    op.drop_index(op.f("ix_missions_assigned_to_user_id"), table_name="missions")
    op.alter_column(
        "missions",
        "description",
        existing_type=sa.String(length=500),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_column("missions", "current_value")
    op.drop_column("missions", "target_value")
    op.drop_column("missions", "mission_type")
    op.drop_column("missions", "assigned_to_user_id")
    # ### end Alembic commands ###
